name: 🖥️ Builds

on:
  push:
    branches: ['master']
    paths:
      - ".github/workflows/{builds, master-builds}.yml"
      - "**/{SConstruct,SCsub,*.py}"
      - "**/*.{hpp,cpp,inc}"
      - "scripts"
      - "deps/**"
      - "tests/**"
      - "AUTHORS.md"
      - "COPYRIGHT"
      - "LICENSE.md"
      - ".pre-commit-config.yaml"
      - "pyproject.toml"
      - ".clang-format"
      - ".clang-tidy"
      - ".gitmodules"
  pull_request:
    branches: ['**']
    paths:
      - ".github/workflows/{builds, master-builds}.yml"
      - "**/{SConstruct,SCsub,*.py}"
      - "**/*.{hpp,cpp,inc}"
      - "scripts"
      - "deps/**"
      - "tests/**"
      - "AUTHORS.md"
      - "COPYRIGHT"
      - "LICENSE.md"
      - ".pre-commit-config.yaml"
      - "pyproject.toml"
      - ".clang-format"
      - ".clang-tidy"
      - ".gitmodules"
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}|${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  static-checks-builds:
    name: Code style, file formatting, and docs
    runs-on: ubuntu-latest
    if: github.run_attempt > 1 || github.event_name == 'workflow_dispatch' || !vars.DISABLE_SIM_BUILDS
    outputs:
      changed-files: '"${{ steps.changed-files.outputs.clangd_all_changed_files }}"' # Wrap with quotes to bookend internal quote separators.
      sources-changed: ${{ steps.changed-files.outputs.sources_any_changed }}
    steps:
      - name: Checkout project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Treeless clone. Slightly less performant than a shallow clone, but makes finding diffs instantaneous.
          filter: tree:0 # See: https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/

      - name: Install APT dependencies
        uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05 # v1.6.0
        with:
          packages: libxml2-utils

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          safe_output: false # Output passed to environment variable to avoid command injection.
          separator: '" "' # To account for paths with spaces, ensure our items are split by quotes internally.
          skip_initial_fetch: true
          files_yaml_from_source_file: .github/changed-files.yml

      - name: Style checks via prek
        uses: j178/prek-action@bdca6f102f98e2b4c7029491a53dfd366469e33d # v2.0.4
        env:
          CHANGED_FILES: '"${{ steps.changed-files.outputs.everything_all_changed_files }}"' # Wrap with quotes to bookend internal quote separators
        with:
          extra-args: --files ${{ env.CHANGED_FILES }}

  build-master:
    name: ${{ matrix.name }}
    needs: static-checks-builds
    if: needs.static-checks-builds.outputs.sources-changed == 'true' || github.event_name != 'pull_request'
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - identifier: windows-debug
            os: windows-latest
            name: 🏁 Windows Debug
            target: template_debug
            platform: windows
            arch: x86_64

          - identifier: windows-release
            os: windows-latest
            name: 🏁 Windows Release
            target: template_release
            platform: windows
            arch: x86_64

          - identifier: macos-debug
            os: macos-latest
            name: 🍎 macOS (universal) Debug
            target: template_debug
            platform: macos
            arch: universal

          - identifier: macos-release
            os: macos-latest
            name: 🍎 macOS (universal) Release
            target: template_release
            platform: macos
            arch: universal

          - identifier: linux-debug
            os: ubuntu-latest
            name: 🐧 Linux Debug
            runner: ubuntu-20.04
            target: template_debug
            platform: linux
            arch: x86_64

          - identifier: linux-release
            os: ubuntu-latest
            name: 🐧 Linux Release
            runner: ubuntu-20.04
            target: template_release
            platform: linux
            arch: x86_64

    uses: ./.github/workflows/reusable-build.yml
    with:
      identifier: ${{ matrix.identifier }}
      os: ${{ matrix.runner || matrix.os }}
      name: ${{ matrix.name }}
      target: ${{ matrix.target }}
      platform: ${{ matrix.platform }}
      arch: ${{ matrix.arch }}
      merge-library-files: true