name: Dependabot Auto-Label
on:
  pull_request:
    types: opened
    branches: master
    paths:
      - deps/openvic-dataloader
      - deps/lexy-vdf

permissions:
  pull-requests: write
  issues: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Shallow Clone
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1 # See: https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/
          persist-credentials: false

      - name: Fetch dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add custom labels based on dependency name
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          DEPENDENCY_NAME: ${{ steps.metadata.outputs.dependency-names }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          if [[ "$DEPENDENCY_NAME" == "deps/openvic-dataloader" ]]; then
            gh pr edit "$PR_URL" --add-label "topic:dataloader"
          elif [[ "$DEPENDENCY_NAME" == "deps/lexy-vdf" ]]; then
            gh pr edit "$PR_URL" --add-label "topic:dataloader"
          fi
