name: 🖥️ Reusable Build

on:
  workflow_call:
    inputs:
      identifier:
        required: true
        type: string
      os:
        required: true
        type: string
      name:
        required: true
        type: string
      target:
        required: true
        type: string
      platform:
        required: true
        type: string
      arch:
        required: true
        type: string
      scons-flags:
        required: false
        default: 'build_ovsim_library=yes build_ovsim_benchmarks=yes'
        type: string
      base-branch:
        required: false
        default: 'master'
        type: string
      merge-library-files:
        required: false
        default: false
        type: boolean
    secrets:
      ARCHIVE_REPO_TOKEN:
        required: false
      GPG_SIGNING_KEY:
        required: false
      RELEASE_KEY:
        required: false
  workflow_dispatch:
    inputs:
      identifier:
        description: |
          Identifier of this build
        required: true
        type: string
      os:
        description: |
          Platform to run build on
        required: true
        type: string
      name:
        description: |
          Human-readable name of this build
        required: true
        type: string
      target:
        description: |
          Target type to build for
        required: true
        type: choice
        options:
          - template_release
          - template_debug
          - editor
      platform:
        description: |
          Platform to build for
        required: true
        type: choice
        options:
          - windows
          - linux
          - macos
      arch:
        description: |
          Architecture to build for
        required: true
        type: choice
        options:
          - x86_64
          - universal
      scons-flags:
        description: |
          Additional flags to send to SCons
        required: false
        default: 'build_ovsim_library=yes build_ovsim_benchmarks=yes'
        type: string
      cache-base-branch:
        description: |
          Branch to base the cache upon
        required: false
        default: 'master'
        type: string
      merge-library-files:
        description: |
          Whether to merge library files into an archive
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ${{ inputs.os }}
    name: ${{ inputs.name }}
    permissions:
      contents: read
      artifact-metadata: write
    steps:
      - name: Checkout project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false

      - name: Setup build cache
        uses: OpenVicProject/openvic-cache@master
        with:
          cache-name: ${{ inputs.identifier }}
          base-branch: ${{ inputs.cache-base-branch }}
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x"

      - name: Set up SCons
        shell: bash
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          scons --version

      - name: Install APT dependencies
        if: ${{ inputs.platform == 'linux' }}
        uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05 # v1.6.0
        with:
          packages: build-essential pkg-config libtbb-dev

      - name: Linux dependencies
        if: ${{ inputs.platform == 'linux' }}
        run: |
          g++ --version
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12
          sudo update-alternatives --set g++ /usr/bin/g++-12
          g++ --version

      - name: Compile with SCons
        uses: OpenVicProject/openvic-build@master
        with:
          platform: ${{ inputs.platform }}
          target: ${{ inputs.target }}
          sconsflags: arch=${{ inputs.arch }} ${{ inputs.scons-flags }}

      - name: Delete compilation files
        if: ${{ inputs.platform == 'windows' }}
        run: |
          Remove-Item bin/* -Include *.exp,*.pdb -Force

      - name: Upload library artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ github.event.repository.name }}-${{ inputs.identifier }}-library
          path: |
            ${{ github.workspace }}/bin/libopenvic-simulation.*

      - name: Upload executable artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ github.event.repository.name }}-${{ inputs.identifier }}-executable
          path: |
            ${{ github.workspace }}/bin/openvic-simulation.headless.*

  merge-library-files:
    name: 📚 Merge Library Files
    runs-on: ubuntu-latest
    needs: build
    if: inputs.merge-library-files
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          delete-merged: true
          name: ${{ github.event.repository.name }}-library
          pattern: ${{ github.event.repository.name }}-*-library
