#include "DiplomacyDefines.hpp"

using namespace OpenVic;
using namespace OpenVic::NodeTools;

DiplomacyDefines::DiplomacyDefines()
  : peace_cost_add_to_sphere {},
	peace_cost_release_puppet {},
	peace_cost_make_puppet {},
	peace_cost_disarmament {},
	peace_cost_destroy_forts {},
	peace_cost_destroy_naval_bases {},
	peace_cost_reparations {},
	peace_cost_transfer_provinces {},
	peace_cost_remove_cores {},
	peace_cost_prestige {},
	peace_cost_concede {},
	peace_cost_status_quo {},
	peace_cost_annex {},
	peace_cost_demand_state {},
	peace_cost_install_communist_gov_type {},
	peace_cost_uninstall_communist_gov_type {},
	peace_cost_colony {},
	infamy_add_to_sphere {},
	infamy_release_puppet {},
	infamy_make_puppet {},
	infamy_disarmament {},
	infamy_destroy_forts {},
	infamy_destroy_naval_bases {},
	infamy_reparations {},
	infamy_transfer_provinces {},
	infamy_remove_cores {},
	infamy_prestige {},
	infamy_concede {},
	infamy_status_quo {},
	infamy_annex {},
	infamy_demand_state {},
	infamy_install_communist_gov_type {},
	infamy_uninstall_communist_gov_type {},
	infamy_colony {},
	prestige_add_to_sphere_base {},
	prestige_release_puppet_base {},
	prestige_make_puppet_base {},
	prestige_disarmament_base {},
	prestige_destroy_forts_base {},
	prestige_destroy_naval_bases_base {},
	prestige_reparations_base {},
	prestige_transfer_provinces_base {},
	prestige_remove_cores_base {},
	prestige_prestige_base {},
	prestige_concede_base {},
	prestige_status_quo_base {},
	prestige_annex_base {},
	prestige_demand_state_base {},
	prestige_clear_union_sphere_base {},
	prestige_gunboat_base {},
	prestige_install_communist_gov_type_base {},
	prestige_uninstall_communist_gov_type_base {},
	prestige_colony_base {},
	prestige_add_to_sphere {},
	prestige_release_puppet {},
	prestige_make_puppet {},
	prestige_disarmament {},
	prestige_destroy_forts {},
	prestige_destroy_naval_bases {},
	prestige_reparations {},
	prestige_transfer_provinces {},
	prestige_remove_cores {},
	prestige_prestige {},
	prestige_concede {},
	prestige_status_quo {},
	prestige_annex {},
	prestige_demand_state {},
	prestige_clear_union_sphere {},
	prestige_gunboat {},
	prestige_install_communist_gov_type {},
	prestige_uninstall_communist_gov_type {},
	prestige_colony {},
	breaktruce_infamy_add_to_sphere {},
	breaktruce_infamy_release_puppet {},
	breaktruce_infamy_make_puppet {},
	breaktruce_infamy_disarmament {},
	breaktruce_infamy_destroy_forts {},
	breaktruce_infamy_destroy_naval_bases {},
	breaktruce_infamy_reparations {},
	breaktruce_infamy_transfer_provinces {},
	breaktruce_infamy_remove_cores {},
	breaktruce_infamy_prestige {},
	breaktruce_infamy_concede {},
	breaktruce_infamy_status_quo {},
	breaktruce_infamy_annex {},
	breaktruce_infamy_demand_state {},
	breaktruce_infamy_install_communist_gov_type {},
	breaktruce_infamy_uninstall_communist_gov_type {},
	breaktruce_infamy_colony {},
	breaktruce_prestige_add_to_sphere {},
	breaktruce_prestige_release_puppet {},
	breaktruce_prestige_make_puppet {},
	breaktruce_prestige_disarmament {},
	breaktruce_prestige_destroy_forts {},
	breaktruce_prestige_destroy_naval_bases {},
	breaktruce_prestige_reparations {},
	breaktruce_prestige_transfer_provinces {},
	breaktruce_prestige_remove_cores {},
	breaktruce_prestige_prestige {},
	breaktruce_prestige_concede {},
	breaktruce_prestige_status_quo {},
	breaktruce_prestige_annex {},
	breaktruce_prestige_demand_state {},
	breaktruce_prestige_install_communist_gov_type {},
	breaktruce_prestige_uninstall_communist_gov_type {},
	breaktruce_prestige_colony {},
	breaktruce_militancy_add_to_sphere {},
	breaktruce_militancy_release_puppet {},
	breaktruce_militancy_make_puppet {},
	breaktruce_militancy_disarmament {},
	breaktruce_militancy_destroy_forts {},
	breaktruce_militancy_destroy_naval_bases {},
	breaktruce_militancy_reparations {},
	breaktruce_militancy_transfer_provinces {},
	breaktruce_militancy_remove_cores {},
	breaktruce_militancy_prestige {},
	breaktruce_militancy_concede {},
	breaktruce_militancy_status_quo {},
	breaktruce_militancy_annex {},
	breaktruce_militancy_demand_state {},
	breaktruce_militancy_install_communist_gov_type {},
	breaktruce_militancy_uninstall_communist_gov_type {},
	breaktruce_militancy_colony {},
	goodrelation_infamy_add_to_sphere {},
	goodrelation_infamy_release_puppet {},
	goodrelation_infamy_make_puppet {},
	goodrelation_infamy_disarmament {},
	goodrelation_infamy_destroy_forts {},
	goodrelation_infamy_destroy_naval_bases {},
	goodrelation_infamy_reparations {},
	goodrelation_infamy_transfer_provinces {},
	goodrelation_infamy_remove_cores {},
	goodrelation_infamy_prestige {},
	goodrelation_infamy_concede {},
	goodrelation_infamy_status_quo {},
	goodrelation_infamy_annex {},
	goodrelation_infamy_demand_state {},
	goodrelation_infamy_install_communist_gov_type {},
	goodrelation_infamy_uninstall_communist_gov_type {},
	goodrelation_infamy_colony {},
	goodrelation_prestige_add_to_sphere {},
	goodrelation_prestige_release_puppet {},
	goodrelation_prestige_make_puppet {},
	goodrelation_prestige_disarmament {},
	goodrelation_prestige_destroy_forts {},
	goodrelation_prestige_destroy_naval_bases {},
	goodrelation_prestige_reparations {},
	goodrelation_prestige_transfer_provinces {},
	goodrelation_prestige_remove_cores {},
	goodrelation_prestige_prestige {},
	goodrelation_prestige_concede {},
	goodrelation_prestige_status_quo {},
	goodrelation_prestige_annex {},
	goodrelation_prestige_demand_state {},
	goodrelation_prestige_install_communist_gov_type {},
	goodrelation_prestige_uninstall_communist_gov_type {},
	goodrelation_prestige_colony {},
	goodrelation_militancy_add_to_sphere {},
	goodrelation_militancy_release_puppet {},
	goodrelation_militancy_make_puppet {},
	goodrelation_militancy_disarmament {},
	goodrelation_militancy_destroy_forts {},
	goodrelation_militancy_destroy_naval_bases {},
	goodrelation_militancy_reparations {},
	goodrelation_militancy_transfer_provinces {},
	goodrelation_militancy_remove_cores {},
	goodrelation_militancy_prestige {},
	goodrelation_militancy_concede {},
	goodrelation_militancy_status_quo {},
	goodrelation_militancy_annex {},
	goodrelation_militancy_demand_state {},
	goodrelation_militancy_install_communist_gov_type {},
	goodrelation_militancy_uninstall_communist_gov_type {},
	goodrelation_militancy_colony {},
	war_prestige_cost_base {},
	war_prestige_cost_high_prestige {},
	war_prestige_cost_neg_prestige {},
	war_prestige_cost_truce {},
	war_prestige_cost_honor_alliance {},
	war_prestige_cost_honor_guarnatee {},
	war_prestige_cost_uncivilized {},
	war_prestige_cost_core {},
	war_failed_goal_militancy {},
	war_failed_goal_prestige_base {},
	war_failed_goal_prestige {},
	discredit_days {},
	discredit_influence_cost_factor {},
	discredit_influence_gain_factor {},
	banembassy_days {},
	declarewar_relation_on_accept {},
	declarewar_diplomatic_cost {},
	addwargoal_relation_on_accept {},
	addwargoal_diplomatic_cost {},
	add_unjustified_goal_badboy {},
	peace_relation_on_accept {},
	peace_relation_on_decline {},
	peace_diplomatic_cost {},
	alliance_relation_on_accept {},
	alliance_relation_on_decline {},
	alliance_diplomatic_cost {},
	cancelalliance_relation_on_accept {},
	cancelalliance_diplomatic_cost {},
	callally_relation_on_accept {},
	callally_relation_on_decline {},
	callally_diplomatic_cost {},
	askmilaccess_relation_on_accept {},
	askmilaccess_relation_on_decline {},
	askmilaccess_diplomatic_cost {},
	cancelaskmilaccess_relation_on_accept {},
	cancelaskmilaccess_diplomatic_cost {},
	givemilaccess_relation_on_accept {},
	givemilaccess_relation_on_decline {},
	givemilaccess_diplomatic_cost {},
	cancelgivemilaccess_relation_on_accept {},
	cancelgivemilaccess_diplomatic_cost {},
	warsubsidy_relation_on_accept {},
	warsubsidy_diplomatic_cost {},
	cancelwarsubsidy_relation_on_accept {},
	cancelwarsubsidy_diplomatic_cost {},
	discredit_relation_on_accept {},
	discredit_influence_cost {},
	expeladvisors_relation_on_accept {},
	expeladvisors_influence_cost {},
	ceasecolonization_relation_on_accept {},
	ceasecolonization_relation_on_decline {},
	ceasecolonization_diplomatic_cost {},
	banembassy_relation_on_accept {},
	banembassy_influence_cost {},
	increaserelation_relation_on_accept {},
	increaserelation_relation_on_decline {},
	increaserelation_diplomatic_cost {},
	decreaserelation_relation_on_accept {},
	decreaserelation_diplomatic_cost {},
	addtosphere_relation_on_accept {},
	addtosphere_influence_cost {},
	removefromsphere_relation_on_accept {},
	removefromsphere_influence_cost {},
	removefromsphere_prestige_cost {},
	removefromsphere_infamy_cost {},
	increaseopinion_relation_on_accept {},
	increaseopinion_influence_cost {},
	decreaseopinion_relation_on_accept {},
	decreaseopinion_influence_cost {},
	make_cb_diplomatic_cost {},
	make_cb_relation_on_accept {},
	disarmed_penalty {},
	reparations_tax_hit {},
	prestige_reduction_base {},
	prestige_reduction {},
	reparations_duration {},
	min_warscore_to_intervene {},
	min_time_to_intervene {},
	max_warscore_from_battles {},
	gunboat_diplomatic_cost {},
	gunboat_relation_on_accept {},
	wargoal_jingoism_requirement {},
	liberate_state_relation_increase {},
	dishonored_callally_prestige_penalty {},
	base_truce_duration {},
	max_influence {},
	warsubsidies_percent {},
	neighbour_bonus_influence_percent {},
	sphere_neighbour_bonus_influence_percent {},
	other_continent_bonus_influence_percent {},
	puppet_bonus_influence_percent {},
	release_nation_prestige {},
	release_nation_infamy {},
	infamy_clear_union_sphere {},
	breaktruce_infamy_clear_union_sphere {},
	breaktruce_prestige_clear_union_sphere {},
	breaktruce_militancy_clear_union_sphere {},
	goodrelation_infamy_clear_union_sphere {},
	goodrelation_prestige_clear_union_sphere {},
	goodrelation_militancy_clear_union_sphere {},
	peace_cost_clear_union_sphere {},
	good_peace_refusal_militancy {},
	good_peace_refusal_warexh {},
	peace_cost_gunboat {},
	infamy_gunboat {},
	breaktruce_infamy_gunboat {},
	breaktruce_prestige_gunboat {},
	breaktruce_militancy_gunboat {},
	goodrelation_infamy_gunboat {},
	goodrelation_prestige_gunboat {},
	goodrelation_militancy_gunboat {},
	cb_generation_base_speed {},
	cb_generation_speed_bonus_on_colony_competition {},
	cb_generation_speed_bonus_on_colony_competition_troops_presence {},
	make_cb_relation_limit {},
	cb_detection_chance_base {},
	investment_influence_defense {},
	relation_influence_modifier {},
	on_cb_detected_relation_change {},
	gw_intervene_min_relations {},
	gw_intervene_max_exhaustion {},
	gw_justify_cb_badboy_impact {},
	gw_cb_construction_speed {},
	gw_wargoal_jingoism_requirement_mod {},
	gw_warscore_cost_mod {},
	gw_warscore_cost_mod_2 {},
	gw_warscore_2_threshold {},
	tension_decay {},
	tension_from_cb {},
	tension_from_movement {},
	tension_from_movement_max {},
	at_war_tension_decay {},
	tension_on_cb_discovered {},
	tension_on_revolt {},
	tension_while_crisis {},
	crisis_cooldown_duration {},
	crisis_base_chance {},
	crisis_temperature_increase {},
	crisis_offer_diplomatic_cost {},
	crisis_offer_relation_on_accept {},
	crisis_offer_relation_on_decline {},
	crisis_did_not_take_side_prestige_factor_base {},
	crisis_did_not_take_side_prestige_factor_year {},
	crisis_winner_prestige_factor_base {},
	crisis_winner_prestige_factor_year {},
	crisis_winner_relations_impact {},
	back_crisis_diplomatic_cost {},
	back_crisis_relation_on_accept {},
	back_crisis_relation_on_decline {},
	crisis_temperature_on_offer_decline {},
	crisis_temperature_participant_factor {},
	crisis_temperature_on_mobilize {},
	crisis_wargoal_infamy_mult {},
	crisis_wargoal_prestige_mult {},
	crisis_wargoal_militancy_mult {},
	crisis_interest_war_exhaustion_limit {},
	rank_1_tension_decay {},
	rank_2_tension_decay {},
	rank_3_tension_decay {},
	rank_4_tension_decay {},
	rank_5_tension_decay {},
	rank_6_tension_decay {},
	rank_7_tension_decay {},
	rank_8_tension_decay {},
	tws_fulfilled_speed {},
	tws_not_fulfilled_speed {},
	tws_grace_period_days {},
	tws_cb_limit_default {},
	tws_fulfilled_idle_space {},
	tws_battle_min_count {},
	tws_battle_max_aspect {},
	large_population_influence_penalty {},
	lone_backer_prestige_factor {} {}

std::string_view DiplomacyDefines::get_name() const {
	return "diplomacy";
}

node_callback_t DiplomacyDefines::expect_defines() {
	// The key map entries are added in two separate function calls, half each time, as adding them all at once causes a
	// runtime crash, presumably due to a limit on the number of loose lambda functions that can exist at the same time.

	key_map_t key_map;

	add_key_map_entries(
		key_map,
		"PEACE_COST_ADD_TO_SPHERE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(peace_cost_add_to_sphere)),
		"PEACE_COST_RELEASE_PUPPET", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(peace_cost_release_puppet)),
		"PEACE_COST_MAKE_PUPPET", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(peace_cost_make_puppet)),
		"PEACE_COST_DISARMAMENT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(peace_cost_disarmament)),
		"PEACE_COST_DESTROY_FORTS", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(peace_cost_destroy_forts)),
		"PEACE_COST_DESTROY_NAVAL_BASES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(peace_cost_destroy_naval_bases)),
		"PEACE_COST_REPARATIONS", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(peace_cost_reparations)),
		"PEACE_COST_TRANSFER_PROVINCES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(peace_cost_transfer_provinces)),
		"PEACE_COST_REMOVE_CORES", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(peace_cost_remove_cores)),
		"PEACE_COST_PRESTIGE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(peace_cost_prestige)),
		"PEACE_COST_CONCEDE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(peace_cost_concede)),
		"PEACE_COST_STATUS_QUO", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(peace_cost_status_quo)),
		"PEACE_COST_ANNEX", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(peace_cost_annex)),
		"PEACE_COST_DEMAND_STATE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(peace_cost_demand_state)),
		"PEACE_COST_INSTALL_COMMUNIST_GOV_TYPE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(peace_cost_install_communist_gov_type)),
		"PEACE_COST_UNINSTALL_COMMUNIST_GOV_TYPE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(peace_cost_uninstall_communist_gov_type)),
		"PEACE_COST_COLONY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(peace_cost_colony)),
		"INFAMY_ADD_TO_SPHERE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(infamy_add_to_sphere)),
		"INFAMY_RELEASE_PUPPET", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(infamy_release_puppet)),
		"INFAMY_MAKE_PUPPET", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(infamy_make_puppet)),
		"INFAMY_DISARMAMENT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(infamy_disarmament)),
		"INFAMY_DESTROY_FORTS", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(infamy_destroy_forts)),
		"INFAMY_DESTROY_NAVAL_BASES", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(infamy_destroy_naval_bases)),
		"INFAMY_REPARATIONS", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(infamy_reparations)),
		"INFAMY_TRANSFER_PROVINCES", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(infamy_transfer_provinces)),
		"INFAMY_REMOVE_CORES", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(infamy_remove_cores)),
		"INFAMY_PRESTIGE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(infamy_prestige)),
		"INFAMY_CONCEDE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(infamy_concede)),
		"INFAMY_STATUS_QUO", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(infamy_status_quo)),
		"INFAMY_ANNEX", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(infamy_annex)),
		"INFAMY_DEMAND_STATE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(infamy_demand_state)),
		"INFAMY_INSTALL_COMMUNIST_GOV_TYPE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(infamy_install_communist_gov_type)),
		"INFAMY_UNINSTALL_COMMUNIST_GOV_TYPE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(infamy_uninstall_communist_gov_type)),
		"INFAMY_COLONY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(infamy_colony)),
		"PRESTIGE_ADD_TO_SPHERE_BASE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_add_to_sphere_base)),
		"PRESTIGE_RELEASE_PUPPET_BASE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(prestige_release_puppet_base)),
		"PRESTIGE_MAKE_PUPPET_BASE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_make_puppet_base)),
		"PRESTIGE_DISARMAMENT_BASE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_disarmament_base)),
		"PRESTIGE_DESTROY_FORTS_BASE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_destroy_forts_base)),
		"PRESTIGE_DESTROY_NAVAL_BASES_BASE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(prestige_destroy_naval_bases_base)),
		"PRESTIGE_REPARATIONS_BASE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_reparations_base)),
		"PRESTIGE_TRANSFER_PROVINCES_BASE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(prestige_transfer_provinces_base)),
		"PRESTIGE_REMOVE_CORES_BASE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_remove_cores_base)),
		"PRESTIGE_PRESTIGE_BASE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_prestige_base)),
		"PRESTIGE_CONCEDE_BASE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_concede_base)),
		"PRESTIGE_STATUS_QUO_BASE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_status_quo_base)),
		"PRESTIGE_ANNEX_BASE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_annex_base)),
		"PRESTIGE_DEMAND_STATE_BASE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_demand_state_base)),
		"PRESTIGE_CLEAR_UNION_SPHERE_BASE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(prestige_clear_union_sphere_base)),
		"PRESTIGE_GUNBOAT_BASE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_gunboat_base)),
		"PRESTIGE_INSTALL_COMMUNIST_GOV_TYPE_BASE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(prestige_install_communist_gov_type_base)),
		"PRESTIGE_UNINSTALL_COMMUNIST_GOV_TYPE_BASE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(prestige_uninstall_communist_gov_type_base)),
		"PRESTIGE_COLONY_BASE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_colony_base)),
		"PRESTIGE_ADD_TO_SPHERE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_add_to_sphere)),
		"PRESTIGE_RELEASE_PUPPET", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_release_puppet)),
		"PRESTIGE_MAKE_PUPPET", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_make_puppet)),
		"PRESTIGE_DISARMAMENT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_disarmament)),
		"PRESTIGE_DESTROY_FORTS", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_destroy_forts)),
		"PRESTIGE_DESTROY_NAVAL_BASES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(prestige_destroy_naval_bases)),
		"PRESTIGE_REPARATIONS", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_reparations)),
		"PRESTIGE_TRANSFER_PROVINCES", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_transfer_provinces)),
		"PRESTIGE_REMOVE_CORES", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_remove_cores)),
		"PRESTIGE_PRESTIGE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_prestige)),
		"PRESTIGE_CONCEDE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_concede)),
		"PRESTIGE_STATUS_QUO", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_status_quo)),
		"PRESTIGE_ANNEX", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_annex)),
		"PRESTIGE_DEMAND_STATE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_demand_state)),
		"PRESTIGE_CLEAR_UNION_SPHERE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_clear_union_sphere)),
		"PRESTIGE_GUNBOAT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_gunboat)),
		"PRESTIGE_INSTALL_COMMUNIST_GOV_TYPE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(prestige_install_communist_gov_type)),
		"PRESTIGE_UNINSTALL_COMMUNIST_GOV_TYPE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(prestige_uninstall_communist_gov_type)),
		"PRESTIGE_COLONY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_colony)),
		"BREAKTRUCE_INFAMY_ADD_TO_SPHERE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_infamy_add_to_sphere)),
		"BREAKTRUCE_INFAMY_RELEASE_PUPPET", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_infamy_release_puppet)),
		"BREAKTRUCE_INFAMY_MAKE_PUPPET", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_infamy_make_puppet)),
		"BREAKTRUCE_INFAMY_DISARMAMENT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_infamy_disarmament)),
		"BREAKTRUCE_INFAMY_DESTROY_FORTS", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_infamy_destroy_forts)),
		"BREAKTRUCE_INFAMY_DESTROY_NAVAL_BASES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_infamy_destroy_naval_bases)),
		"BREAKTRUCE_INFAMY_REPARATIONS", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_infamy_reparations)),
		"BREAKTRUCE_INFAMY_TRANSFER_PROVINCES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_infamy_transfer_provinces)),
		"BREAKTRUCE_INFAMY_REMOVE_CORES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_infamy_remove_cores)),
		"BREAKTRUCE_INFAMY_PRESTIGE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(breaktruce_infamy_prestige)),
		"BREAKTRUCE_INFAMY_CONCEDE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(breaktruce_infamy_concede)),
		"BREAKTRUCE_INFAMY_STATUS_QUO", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_infamy_status_quo)),
		"BREAKTRUCE_INFAMY_ANNEX", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(breaktruce_infamy_annex)),
		"BREAKTRUCE_INFAMY_DEMAND_STATE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_infamy_demand_state)),
		"BREAKTRUCE_INFAMY_INSTALL_COMMUNIST_GOV_TYPE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_infamy_install_communist_gov_type)),
		"BREAKTRUCE_INFAMY_UNINSTALL_COMMUNIST_GOV_TYPE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_infamy_uninstall_communist_gov_type)),
		"BREAKTRUCE_INFAMY_COLONY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(breaktruce_infamy_colony)),
		"BREAKTRUCE_PRESTIGE_ADD_TO_SPHERE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_prestige_add_to_sphere)),
		"BREAKTRUCE_PRESTIGE_RELEASE_PUPPET", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_prestige_release_puppet)),
		"BREAKTRUCE_PRESTIGE_MAKE_PUPPET", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_prestige_make_puppet)),
		"BREAKTRUCE_PRESTIGE_DISARMAMENT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_prestige_disarmament)),
		"BREAKTRUCE_PRESTIGE_DESTROY_FORTS", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_prestige_destroy_forts)),
		"BREAKTRUCE_PRESTIGE_DESTROY_NAVAL_BASES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_prestige_destroy_naval_bases)),
		"BREAKTRUCE_PRESTIGE_REPARATIONS", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_prestige_reparations)),
		"BREAKTRUCE_PRESTIGE_TRANSFER_PROVINCES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_prestige_transfer_provinces)),
		"BREAKTRUCE_PRESTIGE_REMOVE_CORES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_prestige_remove_cores)),
		"BREAKTRUCE_PRESTIGE_PRESTIGE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_prestige_prestige)),
		"BREAKTRUCE_PRESTIGE_CONCEDE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(breaktruce_prestige_concede)),
		"BREAKTRUCE_PRESTIGE_STATUS_QUO", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_prestige_status_quo)),
		"BREAKTRUCE_PRESTIGE_ANNEX", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(breaktruce_prestige_annex)),
		"BREAKTRUCE_PRESTIGE_DEMAND_STATE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_prestige_demand_state)),
		"BREAKTRUCE_PRESTIGE_INSTALL_COMMUNIST_GOV_TYPE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_prestige_install_communist_gov_type)),
		"BREAKTRUCE_PRESTIGE_UNINSTALL_COMMUNIST_GOV_TYPE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_prestige_uninstall_communist_gov_type)),
		"BREAKTRUCE_PRESTIGE_COLONY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(breaktruce_prestige_colony)),
		"BREAKTRUCE_MILITANCY_ADD_TO_SPHERE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_militancy_add_to_sphere)),
		"BREAKTRUCE_MILITANCY_RELEASE_PUPPET", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_militancy_release_puppet)),
		"BREAKTRUCE_MILITANCY_MAKE_PUPPET", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_militancy_make_puppet)),
		"BREAKTRUCE_MILITANCY_DISARMAMENT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_militancy_disarmament)),
		"BREAKTRUCE_MILITANCY_DESTROY_FORTS", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_militancy_destroy_forts)),
		"BREAKTRUCE_MILITANCY_DESTROY_NAVAL_BASES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_militancy_destroy_naval_bases)),
		"BREAKTRUCE_MILITANCY_REPARATIONS", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_militancy_reparations)),
		"BREAKTRUCE_MILITANCY_TRANSFER_PROVINCES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_militancy_transfer_provinces)),
		"BREAKTRUCE_MILITANCY_REMOVE_CORES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_militancy_remove_cores)),
		"BREAKTRUCE_MILITANCY_PRESTIGE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_militancy_prestige)),
		"BREAKTRUCE_MILITANCY_CONCEDE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_militancy_concede)),
		"BREAKTRUCE_MILITANCY_STATUS_QUO", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_militancy_status_quo)),
		"BREAKTRUCE_MILITANCY_ANNEX", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(breaktruce_militancy_annex)),
		"BREAKTRUCE_MILITANCY_DEMAND_STATE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_militancy_demand_state)),
		"BREAKTRUCE_MILITANCY_INSTALL_COMMUNIST_GOV_TYPE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_militancy_install_communist_gov_type)),
		"BREAKTRUCE_MILITANCY_UNINSTALL_COMMUNIST_GOV_TYPE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_militancy_uninstall_communist_gov_type)),
		"BREAKTRUCE_MILITANCY_COLONY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(breaktruce_militancy_colony)),
		"GOODRELATION_INFAMY_ADD_TO_SPHERE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_infamy_add_to_sphere)),
		"GOODRELATION_INFAMY_RELEASE_PUPPET", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_infamy_release_puppet)),
		"GOODRELATION_INFAMY_MAKE_PUPPET", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_infamy_make_puppet)),
		"GOODRELATION_INFAMY_DISARMAMENT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_infamy_disarmament)),
		"GOODRELATION_INFAMY_DESTROY_FORTS", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_infamy_destroy_forts)),
		"GOODRELATION_INFAMY_DESTROY_NAVAL_BASES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_infamy_destroy_naval_bases)),
		"GOODRELATION_INFAMY_REPARATIONS", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_infamy_reparations)),
		"GOODRELATION_INFAMY_TRANSFER_PROVINCES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_infamy_transfer_provinces)),
		"GOODRELATION_INFAMY_REMOVE_CORES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_infamy_remove_cores)),
		"GOODRELATION_INFAMY_PRESTIGE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_infamy_prestige)),
		"GOODRELATION_INFAMY_CONCEDE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(goodrelation_infamy_concede)),
		"GOODRELATION_INFAMY_STATUS_QUO", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_infamy_status_quo)),
		"GOODRELATION_INFAMY_ANNEX", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(goodrelation_infamy_annex)),
		"GOODRELATION_INFAMY_DEMAND_STATE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_infamy_demand_state)),
		"GOODRELATION_INFAMY_INSTALL_COMMUNIST_GOV_TYPE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_infamy_install_communist_gov_type)),
		"GOODRELATION_INFAMY_UNINSTALL_COMMUNIST_GOV_TYPE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_infamy_uninstall_communist_gov_type)),
		"GOODRELATION_INFAMY_COLONY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(goodrelation_infamy_colony)),
		"GOODRELATION_PRESTIGE_ADD_TO_SPHERE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_prestige_add_to_sphere)),
		"GOODRELATION_PRESTIGE_RELEASE_PUPPET", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_prestige_release_puppet)),
		"GOODRELATION_PRESTIGE_MAKE_PUPPET", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_prestige_make_puppet)),
		"GOODRELATION_PRESTIGE_DISARMAMENT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_prestige_disarmament)),
		"GOODRELATION_PRESTIGE_DESTROY_FORTS", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_prestige_destroy_forts)),
		"GOODRELATION_PRESTIGE_DESTROY_NAVAL_BASES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_prestige_destroy_naval_bases)),
		"GOODRELATION_PRESTIGE_REPARATIONS", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_prestige_reparations)),
		"GOODRELATION_PRESTIGE_TRANSFER_PROVINCES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_prestige_transfer_provinces)),
		"GOODRELATION_PRESTIGE_REMOVE_CORES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_prestige_remove_cores)),
		"GOODRELATION_PRESTIGE_PRESTIGE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_prestige_prestige)),
		"GOODRELATION_PRESTIGE_CONCEDE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_prestige_concede)),
		"GOODRELATION_PRESTIGE_STATUS_QUO", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_prestige_status_quo)),
		"GOODRELATION_PRESTIGE_ANNEX", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(goodrelation_prestige_annex)),
		"GOODRELATION_PRESTIGE_DEMAND_STATE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_prestige_demand_state)),
		"GOODRELATION_PRESTIGE_INSTALL_COMMUNIST_GOV_TYPE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_prestige_install_communist_gov_type)),
		"GOODRELATION_PRESTIGE_UNINSTALL_COMMUNIST_GOV_TYPE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_prestige_uninstall_communist_gov_type)),
		"GOODRELATION_PRESTIGE_COLONY", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_prestige_colony)),
		"GOODRELATION_MILITANCY_ADD_TO_SPHERE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_add_to_sphere)),
		"GOODRELATION_MILITANCY_RELEASE_PUPPET", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_release_puppet)),
		"GOODRELATION_MILITANCY_MAKE_PUPPET", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_make_puppet)),
		"GOODRELATION_MILITANCY_DISARMAMENT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_disarmament)),
		"GOODRELATION_MILITANCY_DESTROY_FORTS", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_destroy_forts)),
		"GOODRELATION_MILITANCY_DESTROY_NAVAL_BASES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_destroy_naval_bases)),
		"GOODRELATION_MILITANCY_REPARATIONS", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_reparations)),
		"GOODRELATION_MILITANCY_TRANSFER_PROVINCES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_transfer_provinces)),
		"GOODRELATION_MILITANCY_REMOVE_CORES", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_remove_cores)),
		"GOODRELATION_MILITANCY_PRESTIGE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_prestige)),
		"GOODRELATION_MILITANCY_CONCEDE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_concede)),
		"GOODRELATION_MILITANCY_STATUS_QUO", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_status_quo)),
		"GOODRELATION_MILITANCY_ANNEX", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_annex)),
		"GOODRELATION_MILITANCY_DEMAND_STATE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_demand_state)),
		"GOODRELATION_MILITANCY_INSTALL_COMMUNIST_GOV_TYPE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_install_communist_gov_type)),
		"GOODRELATION_MILITANCY_UNINSTALL_COMMUNIST_GOV_TYPE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_uninstall_communist_gov_type)),
		"GOODRELATION_MILITANCY_COLONY", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_colony))
	);

	add_key_map_entries(
		key_map,
		"WAR_PRESTIGE_COST_BASE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(war_prestige_cost_base)),
		"WAR_PRESTIGE_COST_HIGH_PRESTIGE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(war_prestige_cost_high_prestige)),
		"WAR_PRESTIGE_COST_NEG_PRESTIGE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(war_prestige_cost_neg_prestige)),
		"WAR_PRESTIGE_COST_TRUCE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(war_prestige_cost_truce)),
		"WAR_PRESTIGE_COST_HONOR_ALLIANCE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(war_prestige_cost_honor_alliance)),
		"WAR_PRESTIGE_COST_HONOR_GUARNATEE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(war_prestige_cost_honor_guarnatee)),
		"WAR_PRESTIGE_COST_UNCIVILIZED", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(war_prestige_cost_uncivilized)),
		"WAR_PRESTIGE_COST_CORE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(war_prestige_cost_core)),
		"WAR_FAILED_GOAL_MILITANCY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(war_failed_goal_militancy)),
		"WAR_FAILED_GOAL_PRESTIGE_BASE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(war_failed_goal_prestige_base)),
		"WAR_FAILED_GOAL_PRESTIGE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(war_failed_goal_prestige)),
		"DISCREDIT_DAYS", ONE_EXACTLY, expect_days(assign_variable_callback(discredit_days)),
		"DISCREDIT_INFLUENCE_COST_FACTOR", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(discredit_influence_cost_factor)),
		"DISCREDIT_INFLUENCE_GAIN_FACTOR", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(discredit_influence_gain_factor)),
		"BANEMBASSY_DAYS", ONE_EXACTLY, expect_days(assign_variable_callback(banembassy_days)),
		"DECLAREWAR_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(declarewar_relation_on_accept)),
		"DECLAREWAR_DIPLOMATIC_COST", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(declarewar_diplomatic_cost)),
		"ADDWARGOAL_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(addwargoal_relation_on_accept)),
		"ADDWARGOAL_DIPLOMATIC_COST", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(addwargoal_diplomatic_cost)),
		"ADD_UNJUSTIFIED_GOAL_BADBOY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(add_unjustified_goal_badboy)),
		"PEACE_RELATION_ON_ACCEPT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(peace_relation_on_accept)),
		"PEACE_RELATION_ON_DECLINE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(peace_relation_on_decline)),
		"PEACE_DIPLOMATIC_COST", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(peace_diplomatic_cost)),
		"ALLIANCE_RELATION_ON_ACCEPT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(alliance_relation_on_accept)),
		"ALLIANCE_RELATION_ON_DECLINE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(alliance_relation_on_decline)),
		"ALLIANCE_DIPLOMATIC_COST", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(alliance_diplomatic_cost)),
		"CANCELALLIANCE_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(cancelalliance_relation_on_accept)),
		"CANCELALLIANCE_DIPLOMATIC_COST", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(cancelalliance_diplomatic_cost)),
		"CALLALLY_RELATION_ON_ACCEPT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(callally_relation_on_accept)),
		"CALLALLY_RELATION_ON_DECLINE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(callally_relation_on_decline)),
		"CALLALLY_DIPLOMATIC_COST", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(callally_diplomatic_cost)),
		"ASKMILACCESS_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(askmilaccess_relation_on_accept)),
		"ASKMILACCESS_RELATION_ON_DECLINE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(askmilaccess_relation_on_decline)),
		"ASKMILACCESS_DIPLOMATIC_COST", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(askmilaccess_diplomatic_cost)),
		"CANCELASKMILACCESS_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(cancelaskmilaccess_relation_on_accept)),
		"CANCELASKMILACCESS_DIPLOMATIC_COST", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(cancelaskmilaccess_diplomatic_cost)),
		"GIVEMILACCESS_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(givemilaccess_relation_on_accept)),
		"GIVEMILACCESS_RELATION_ON_DECLINE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(givemilaccess_relation_on_decline)),
		"GIVEMILACCESS_DIPLOMATIC_COST", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(givemilaccess_diplomatic_cost)),
		"CANCELGIVEMILACCESS_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(cancelgivemilaccess_relation_on_accept)),
		"CANCELGIVEMILACCESS_DIPLOMATIC_COST", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(cancelgivemilaccess_diplomatic_cost)),
		"WARSUBSIDY_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(warsubsidy_relation_on_accept)),
		"WARSUBSIDY_DIPLOMATIC_COST", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(warsubsidy_diplomatic_cost)),
		"CANCELWARSUBSIDY_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(cancelwarsubsidy_relation_on_accept)),
		"CANCELWARSUBSIDY_DIPLOMATIC_COST", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(cancelwarsubsidy_diplomatic_cost)),
		"DISCREDIT_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(discredit_relation_on_accept)),
		"DISCREDIT_INFLUENCE_COST", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(discredit_influence_cost)),
		"EXPELADVISORS_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(expeladvisors_relation_on_accept)),
		"EXPELADVISORS_INFLUENCE_COST", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(expeladvisors_influence_cost)),
		"CEASECOLONIZATION_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(ceasecolonization_relation_on_accept)),
		"CEASECOLONIZATION_RELATION_ON_DECLINE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(ceasecolonization_relation_on_decline)),
		"CEASECOLONIZATION_DIPLOMATIC_COST", ONE_OR_MORE, // Appears twice in vanilla!
			expect_fixed_point(assign_variable_callback(ceasecolonization_diplomatic_cost)),
		"BANEMBASSY_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(banembassy_relation_on_accept)),
		"BANEMBASSY_INFLUENCE_COST", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(banembassy_influence_cost)),
		"INCREASERELATION_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(increaserelation_relation_on_accept)),
		"INCREASERELATION_RELATION_ON_DECLINE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(increaserelation_relation_on_decline)),
		"INCREASERELATION_DIPLOMATIC_COST", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(increaserelation_diplomatic_cost)),
		"DECREASERELATION_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(decreaserelation_relation_on_accept)),
		"DECREASERELATION_DIPLOMATIC_COST", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(decreaserelation_diplomatic_cost)),
		"ADDTOSPHERE_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(addtosphere_relation_on_accept)),
		"ADDTOSPHERE_INFLUENCE_COST", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(addtosphere_influence_cost)),
		"REMOVEFROMSPHERE_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(removefromsphere_relation_on_accept)),
		"REMOVEFROMSPHERE_INFLUENCE_COST", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(removefromsphere_influence_cost)),
		"REMOVEFROMSPHERE_PRESTIGE_COST", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(removefromsphere_prestige_cost)),
		"REMOVEFROMSPHERE_INFAMY_COST", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(removefromsphere_infamy_cost)),
		"INCREASEOPINION_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(increaseopinion_relation_on_accept)),
		"INCREASEOPINION_INFLUENCE_COST", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(increaseopinion_influence_cost)),
		"DECREASEOPINION_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(decreaseopinion_relation_on_accept)),
		"DECREASEOPINION_INFLUENCE_COST", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(decreaseopinion_influence_cost)),
		"MAKE_CB_DIPLOMATIC_COST", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(make_cb_diplomatic_cost)),
		"MAKE_CB_RELATION_ON_ACCEPT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(make_cb_relation_on_accept)),
		"DISARMAMENT_ARMY_HIT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(disarmed_penalty)),
		"REPARATIONS_TAX_HIT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(reparations_tax_hit)),
		"PRESTIGE_REDUCTION_BASE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_reduction_base)),
		"PRESTIGE_REDUCTION", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(prestige_reduction)),
		"REPARATIONS_YEARS", ONE_EXACTLY, expect_years(assign_variable_callback(reparations_duration)),
		"MIN_WARSCORE_TO_INTERVENE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(min_warscore_to_intervene)),
		"MIN_MONTHS_TO_INTERVENE", ONE_EXACTLY, expect_months(assign_variable_callback(min_time_to_intervene)),
		"MAX_WARSCORE_FROM_BATTLES", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(max_warscore_from_battles)),
		"GUNBOAT_DIPLOMATIC_COST", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(gunboat_diplomatic_cost)),
		"GUNBOAT_RELATION_ON_ACCEPT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(gunboat_relation_on_accept)),
		"WARGOAL_JINGOISM_REQUIREMENT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(wargoal_jingoism_requirement)),
		"LIBERATE_STATE_RELATION_INCREASE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(liberate_state_relation_increase)),
		"DISHONORED_CALLALLY_PRESTIGE_PENALTY", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(dishonored_callally_prestige_penalty)),
		"BASE_TRUCE_MONTHS", ONE_EXACTLY, expect_months(assign_variable_callback(base_truce_duration)),
		"MAX_INFLUENCE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(max_influence)),
		"WARSUBSIDIES_PERCENT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(warsubsidies_percent)),
		"NEIGHBOUR_BONUS_INFLUENCE_PERCENT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(neighbour_bonus_influence_percent)),
		"SPHERE_NEIGHBOUR_BONUS_INFLUENCE_PERCENT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(sphere_neighbour_bonus_influence_percent)),
		"OTHER_CONTINENT_BONUS_INFLUENCE_PERCENT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(other_continent_bonus_influence_percent)),
		"PUPPET_BONUS_INFLUENCE_PERCENT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(puppet_bonus_influence_percent)),
		"RELEASE_NATION_PRESTIGE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(release_nation_prestige)),
		"RELEASE_NATION_INFAMY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(release_nation_infamy)),
		"INFAMY_CLEAR_UNION_SPHERE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(infamy_clear_union_sphere)),
		"BREAKTRUCE_INFAMY_CLEAR_UNION_SPHERE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_infamy_clear_union_sphere)),
		"BREAKTRUCE_PRESTIGE_CLEAR_UNION_SPHERE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_prestige_clear_union_sphere)),
		"BREAKTRUCE_MILITANCY_CLEAR_UNION_SPHERE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_militancy_clear_union_sphere)),
		"GOODRELATION_INFAMY_CLEAR_UNION_SPHERE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_infamy_clear_union_sphere)),
		"GOODRELATION_PRESTIGE_CLEAR_UNION_SPHERE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_prestige_clear_union_sphere)),
		"GOODRELATION_MILITANCY_CLEAR_UNION_SPHERE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_clear_union_sphere)),
		"PEACE_COST_CLEAR_UNION_SPHERE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(peace_cost_clear_union_sphere)),
		"GOOD_PEACE_REFUSAL_MILITANCY", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(good_peace_refusal_militancy)),
		"GOOD_PEACE_REFUSAL_WAREXH", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(good_peace_refusal_warexh)),
		"PEACE_COST_GUNBOAT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(peace_cost_gunboat)),
		"INFAMY_GUNBOAT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(infamy_gunboat)),
		"BREAKTRUCE_INFAMY_GUNBOAT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(breaktruce_infamy_gunboat)),
		"BREAKTRUCE_PRESTIGE_GUNBOAT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(breaktruce_prestige_gunboat)),
		"BREAKTRUCE_MILITANCY_GUNBOAT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(breaktruce_militancy_gunboat)),
		"GOODRELATION_INFAMY_GUNBOAT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(goodrelation_infamy_gunboat)),
		"GOODRELATION_PRESTIGE_GUNBOAT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_prestige_gunboat)),
		"GOODRELATION_MILITANCY_GUNBOAT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(goodrelation_militancy_gunboat)),
		"CB_GENERATION_BASE_SPEED", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(cb_generation_base_speed)),
		"CB_GENERATION_SPEED_BONUS_ON_COLONY_COMPETITION", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(cb_generation_speed_bonus_on_colony_competition)),
		"CB_GENERATION_SPEED_BONUS_ON_COLONY_COMPETITION_TROOPS_PRESENCE", ONE_EXACTLY, expect_fixed_point(
			assign_variable_callback(cb_generation_speed_bonus_on_colony_competition_troops_presence)
		),
		"MAKE_CB_RELATION_LIMIT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(make_cb_relation_limit)),
		"CB_DETECTION_CHANCE_BASE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(cb_detection_chance_base)),
		"INVESTMENT_INFLUENCE_DEFENSE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(investment_influence_defense)),
		"RELATION_INFLUENCE_MODIFIER", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(relation_influence_modifier)),
		"ON_CB_DETECTED_RELATION_CHANGE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(on_cb_detected_relation_change)),
		"GW_INTERVENE_MIN_RELATIONS", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(gw_intervene_min_relations)),
		"GW_INTERVENE_MAX_EXHAUSTION", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(gw_intervene_max_exhaustion)),
		"GW_JUSTIFY_CB_BADBOY_IMPACT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(gw_justify_cb_badboy_impact)),
		"GW_CB_CONSTRUCTION_SPEED", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(gw_cb_construction_speed)),
		"GW_WARGOAL_JINGOISM_REQUIREMENT_MOD", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(gw_wargoal_jingoism_requirement_mod)),
		"GW_WARSCORE_COST_MOD", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(gw_warscore_cost_mod)),
		"GW_WARSCORE_COST_MOD_2", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(gw_warscore_cost_mod_2)),
		"GW_WARSCORE_2_THRESHOLD", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(gw_warscore_2_threshold)),
		"TENSION_DECAY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(tension_decay)),
		"TENSION_FROM_CB", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(tension_from_cb)),
		"TENSION_FROM_MOVEMENT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(tension_from_movement)),
		"TENSION_FROM_MOVEMENT_MAX", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(tension_from_movement_max)),
		"AT_WAR_TENSION_DECAY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(at_war_tension_decay)),
		"TENSION_ON_CB_DISCOVERED", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(tension_on_cb_discovered)),
		"TENSION_ON_REVOLT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(tension_on_revolt)),
		"TENSION_WHILE_CRISIS", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(tension_while_crisis)),
		"CRISIS_COOLDOWN_MONTHS", ONE_EXACTLY, expect_months(assign_variable_callback(crisis_cooldown_duration)),
		"CRISIS_BASE_CHANCE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(crisis_base_chance)),
		"CRISIS_TEMPERATURE_INCREASE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(crisis_temperature_increase)),
		"CRISIS_OFFER_DIPLOMATIC_COST", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(crisis_offer_diplomatic_cost)),
		"CRISIS_OFFER_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(crisis_offer_relation_on_accept)),
		"CRISIS_OFFER_RELATION_ON_DECLINE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(crisis_offer_relation_on_decline)),
		"CRISIS_DID_NOT_TAKE_SIDE_PRESTIGE_FACTOR_BASE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(crisis_did_not_take_side_prestige_factor_base)),
		"CRISIS_DID_NOT_TAKE_SIDE_PRESTIGE_FACTOR_YEAR", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(crisis_did_not_take_side_prestige_factor_year)),
		"CRISIS_WINNER_PRESTIGE_FACTOR_BASE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(crisis_winner_prestige_factor_base)),
		"CRISIS_WINNER_PRESTIGE_FACTOR_YEAR", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(crisis_winner_prestige_factor_year)),
		"CRISIS_WINNER_RELATIONS_IMPACT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(crisis_winner_relations_impact)),
		"BACK_CRISIS_DIPLOMATIC_COST", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(back_crisis_diplomatic_cost)),
		"BACK_CRISIS_RELATION_ON_ACCEPT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(back_crisis_relation_on_accept)),
		"BACK_CRISIS_RELATION_ON_DECLINE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(back_crisis_relation_on_decline)),
		"CRISIS_TEMPERATURE_ON_OFFER_DECLINE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(crisis_temperature_on_offer_decline)),
		"CRISIS_TEMPERATURE_PARTICIPANT_FACTOR", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(crisis_temperature_participant_factor)),
		"CRISIS_TEMPERATURE_ON_MOBILIZE", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(crisis_temperature_on_mobilize)),
		"CRISIS_WARGOAL_INFAMY_MULT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(crisis_wargoal_infamy_mult)),
		"CRISIS_WARGOAL_PRESTIGE_MULT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(crisis_wargoal_prestige_mult)),
		"CRISIS_WARGOAL_MILITANCY_MULT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(crisis_wargoal_militancy_mult)),
		"CRISIS_INTEREST_WAR_EXHAUSTION_LIMIT", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(crisis_interest_war_exhaustion_limit)),
		"RANK_1_TENSION_DECAY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(rank_1_tension_decay)),
		"RANK_2_TENSION_DECAY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(rank_2_tension_decay)),
		"RANK_3_TENSION_DECAY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(rank_3_tension_decay)),
		"RANK_4_TENSION_DECAY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(rank_4_tension_decay)),
		"RANK_5_TENSION_DECAY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(rank_5_tension_decay)),
		"RANK_6_TENSION_DECAY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(rank_6_tension_decay)),
		"RANK_7_TENSION_DECAY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(rank_7_tension_decay)),
		"RANK_8_TENSION_DECAY", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(rank_8_tension_decay)),
		"TWS_FULFILLED_SPEED", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(tws_fulfilled_speed)),
		"TWS_NOT_FULFILLED_SPEED", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(tws_not_fulfilled_speed)),
		"TWS_GRACE_PERIOD_DAYS", ONE_EXACTLY, expect_days(assign_variable_callback(tws_grace_period_days)),
		"TWS_CB_LIMIT_DEFAULT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(tws_cb_limit_default)),
		"TWS_FULFILLED_IDLE_SPACE", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(tws_fulfilled_idle_space)),
		"TWS_BATTLE_MIN_COUNT", ONE_EXACTLY, expect_uint(assign_variable_callback(tws_battle_min_count)),
		"TWS_BATTLE_MAX_ASPECT", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(tws_battle_max_aspect)),
		"LARGE_POPULATION_INFLUENCE_PENALTY", ONE_EXACTLY,
			expect_fixed_point(assign_variable_callback(large_population_influence_penalty)),
		"LONE_BACKER_PRESTIGE_FACTOR", ONE_EXACTLY, expect_fixed_point(assign_variable_callback(lone_backer_prestige_factor))
	);

	return expect_dictionary_key_map(std::move(key_map));
}
